// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SiteVendas.Model
{
    public partial class tb_endereco
    {
        public tb_endereco()
        {
            tb_cadastro_cliente = new HashSet<tb_cadastro_cliente>();
            tb_dados_empresa = new HashSet<tb_dados_empresa>();
        }

        [Key]
        public int id_endereco { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_tipo { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_cep { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_estado { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_logradouro { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_numero { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string ed_complemento { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_bairro { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string ed_cidade { get; set; }

        [InverseProperty("fk_enderecoNavigation")]
        public virtual ICollection<tb_cadastro_cliente> tb_cadastro_cliente { get; set; }
        [InverseProperty("fk_enderecoNavigation")]
        public virtual ICollection<tb_dados_empresa> tb_dados_empresa { get; set; }
    }
}